### ISSUE TITLE
Create the initial Pratt parser

### ISSUE THREAD

**Issue by doublevcodes** [cat-dev-group/meow.c#1]
Meow is still in it’s early stages of development, like... *really early!*

But what do we need to get up onto it’s feet is a basic parser. At it’s most fundamental level, the parser is going to take a stream of tokens and output an AST, or Abstract Syntax Tree. This parser will be a Pratt parser with all the whistles and bells: operator precedence and other stuff.

This initial iteration of the hand-written parser doesn’t have to be the best, fastest parser out there (although no objections if it is), it simply has to **work**. It can be improved upon at a future date.

In order for work to begin on the parser, we first need to finish the lexer, but we’re on the right path!

**Comment by AbooMinister25** [comment]
We don't need to-do issues - rather just have a roadmap issue.
