### ISSUE TITLE
Compile our AST into Bytecode

### ISSUE THREAD

**Issue by doublevcodes** [cat-dev-group/meow.c#2]
That's right, we need a... *compiler*! Since Meow is first lexed into tokens, then parsed into an AST, the next step is to compile the AST into VM-readable bytecode.

The compiler will be using converting out AST into bytecode but since we're all so ✨ *tremendously marvelous* ✨, this compiler will also feature multiple out of the box optimizations such as the removal of dead code and unusual variables and functions. We also aim for the compiler to have a few built in warnings which can be configured to emit when certain anti-practices are present in the code.

I wish you all the best in making a compiler. ___Godspeed___

**Comment by AbooMinister25** [comment]
We don't need to-do issues - rather just have a roadmap issue.
