### ISSUE TITLE
Implement a VM that works

### ISSUE THREAD

**Issue by doublevcodes** [cat-dev-group/meow.c#3]
A VM is a Virtual Machine. Yes, most people ~~dream~~ think of running *Arch Linux* on their computer in on of these, in the hope that it won't harm their system.

*We're making a VM too!* **How exciting 🚀**... but you won't be running Arch on it, you'll be doing something better. *Executing bytecode!* Bytecode, which was generated by our compiler in #2, has to be ***run*** in a VM.

Our VM will store *3 main things* in it's ✨ amazing ✨ virtual memory: **a stack**, which will have a maximum of 256 items per frame; **a chunk**, which will be a series of bytecode, however the chunk stores these as bytes; **a program counter**, which tells the VM whereabouts in our program we've got to and need to go so far.

*Now start building this thing!* soon:tm:

**Comment by AbooMinister25** [comment]
We don't need to-do issues - rather just have a roadmap issue.
